name: Lint-deployment
on:
  push:
    branches:
      - main
      - master
      - dev
  workflow_dispatch:
  pull_request:
    types:
      - closed
      - opened
  # paths-ignore:
  #   - "./github/workflow/*"
jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: clone-repo
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~./npm
          keys: deps-node-modules-${{hashFiles('**/package.lock.json')}}
      - name: install-dependencies
        run: npm ci
      - name: test-code
        run: npm test
      - name: lint-code
        run: npm run test
      - name: build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist
      # - name:
  deployment:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifacts@v4
        id: artifact-download
        with:
          path: artifacts
      - name: deploy
        if: failure() && steps.artifact-download.outcome == 'failure'
        run: echo "deployed successfully"
      # - name:
